### ISSUE TITLE
USB Not Recognized, it sees it as Bluetooth 

### ISSUE THREAD

**Issue by M1K3rSz** [LaserWeb/LaserWeb4-Binaries#1]
Hi cannot connect usb t Imac 27"
![schermafbeelding 2017-03-17 om 14 20 12](https://cloud.githubusercontent.com/assets/25887696/24053187/81866bb0-0b38-11e7-8eca-9b4dcca114ac.png)

**Comment by openhardwarecoza** [comment]
Likely not a bug, so doesnt belong on github

Lw has no control over your OS. If your OS doesnt show the port it means its between hardware and OS

**Comment by cojarbi** [comment]
That's standard on a Mac. What board do you have

**Comment by openhardwarecoza** [comment]
@cojarbi don't allow this to continue here. Github for developers and real bugs. Users and their imagination can go to support forum
