### ISSUE TITLE
Documentation site closed down ("CNCPRO.CO"). 

### ISSUE THREAD

**Issue by cyberchucktx** [LaserWeb/LaserWeb4-Binaries#1]
A note: the "Documentation" section on this GITHUB archive says "Head over to http://cncpro.co". 

When I tried to go there as of the date of this posting (9/25/17) the site says

 "Looking for LaserWeb?  no longer here... CNCpro.co is retired"

FYI<

**Comment by jorgerobles** [comment]
Thank you, will check.
