### ISSUE TITLE
v4.0.994-130 windows release shows up as v4.0.993-130 after update???

### ISSUE THREAD

**Issue by tmenet** [LaserWeb/LaserWeb4-Binaries#15]
I was running v4.0.993-130 and  I got notification there was a new release. I downloaded the new release .exe file and ran it. I got the expected windows 10 warning so I continued on and proceeded with the download of v4.0.994-130. The downloaded completed and automatically launched Laserweb however at the top left it still says Laserweb 4.0.993 ?  I am not sure if you have simply forgotten to change the version number within the program or if you renamed  the wrong installer.

Can you verify or am I doing something wrong during install?

I could not find any release notes to see what has changed.

**Comment by jorgerobles** [comment]
Yes, seems the descriptor for version was not updated whatever reason.

Please ignore it.
