### ISSUE TITLE
Machine Settings Left x offest not working

### ISSUE THREAD

**Issue by DOUG888** [LaserWeb/LaserWeb4-Binaries#16]
Laserweb version 996-130 and before.
in settings/machine/machine left x
this works for -1 but anything smaller (-2/-2.25/-3/etc) does not make any difference.
I am running as a GRBL machine.
Doug

**Comment by cprezzi** [comment]
Please do not open software issues in this repo as it is only used for distributing the binary installers. Use https://github.com/LaserWeb/LaserWeb4 instead.
