### ISSUE TITLE
generating "laser cut" paths slow and not complete

### ISSUE THREAD

**Issue by valdasa** [LaserWeb/LaserWeb4-Binaries#17]
when "laser cut" generated from large dxf or svg file most of paths are missing and takes very long time to generate. If i import same file with laserweb 3 takes couple of seconds and generates all paths. Files are exported with corel draw.

**Comment by cprezzi** [comment]
Same issue like https://github.com/LaserWeb/LaserWeb4/issues/514!

PS: Please do not open LW4 issues in this repo as it is only used for distributing the binary installers.
