### ISSUE TITLE
LaserWeb ARM 64

### ISSUE THREAD

**Issue by kasp1** [LaserWeb/LaserWeb4-Binaries#18]
Hey guys, is there any way I can get LaserWeb running on the latest Raspberry Pi (3B+)?

**Comment by cprezzi** [comment]
You can just install the server part (lw.comm-server) on a Raspberry Pi, but connect it with the frontend from a PC.  (see: https://github.com/LaserWeb/lw.comm-server/wiki/Manual-Installation-(RasPi))

**Comment by kasp1** [comment]
Thanks for the reply. My goal was to run a laser from an RPI so I wouldn't have to always come with a laptop. :-)

**Comment by cprezzi** [comment]
The LW4 frontend doesn't work properly on the raspi itself (not enough power/ram).
