### ISSUE TITLE
Include x32 or x64 into window builds

### ISSUE THREAD

**Issue by DarklyLabs** [LaserWeb/LaserWeb4-Binaries#2]
Is it possible to include 'x32' and 'x64' into the windows build filenames to help distinguish them?

This happens in the linux builds and is very useful.

**Comment by openhardwarecoza** [comment]
The waya we use Electron_builder we cannot make it name the file we want (opposite side of the coin it names the linux version lw.comms-server.... instead of Laserweb... which I also cant fix)

We'll need to switch to using Electron_builder programmatically if we wanted to
