### ISSUE TITLE
Blank screen at startup

### ISSUE THREAD

**Issue by M1K3rSz** [LaserWeb/LaserWeb4-Binaries#3]
after re-installing latest Laserweb.dmg, blank screen at startup, deleted all files and folders on iMac and re-install again without any succes.

**Comment by jorgerobles** [comment]
Same as #2, on mac.
Sorry, but currently we have no way to know what is happening inside your computer (Missed that Hogwarts class)
I personally develop and test on a Sierra OSX with GTX760 with no problem.
In order the issues to be attended, System information (at least) is needed.

please remove  ~/Library/Application\ Support/lw.comm-server/ and try again

**Comment by M1K3rSz** [comment]
Ah Yess , offcourse ,sorry i had to post some more about my System info ;)
As told i removed lw.comm-server folder , that did the trick!

How it all happend i dont know , but thanks for the quick support
