### ISSUE TITLE
Windows 10 - error: Listening EACCES 0.0.0.0:8000

### ISSUE THREAD

**Issue by Parkrcz** [LaserWeb/LaserWeb4-Binaries#31]
Hello,
I´v installed LaserWeb4 app on a few devices without issue, but I am struggling to make it work on my PC. I am getting error message: "error: Listening EACCES 0.0.0.0:8000", it looks like ports are in collision. I´v checked this and I found that port 8000 is already in use, but unfortunately it´s System and I´am not able to kill it. Is there a way, how to change port number for this app manually?

Thank You

Petr

**Comment by cprezzi** [comment]
You can change the default port by creating a textfile named `.env` (nothing in front of the dot!) and enter the line `WEB_PORT=8001` (change 8001 to your preferred port).

**Comment by frank-pian** [comment]
I have same problem in v4.0.998-136. I put .env in installation directory. But it doesn't work.
![微信截图_20210726195047](https://user-images.githubusercontent.com/8214804/126984365-0615fa8c-fc65-4e5e-9c9a-9e5b2401bed5.png)

**Comment by cprezzi** [comment]
I checked it with version 4.0.999-138 and the .env file works corectly. Are you sure your .env file doesn't have any additional extention like .txt, which is just hidden by your file explorer default settings (hide known filetypes)?
