### ISSUE TITLE
Laser power weak running job, but tests fine.

### ISSUE THREAD

**Issue by TijuanaKez** [LaserWeb/LaserWeb4-Binaries#39]
So when I add a test job line cut at %100 power, it doesn't burn and the laser just even looks dim.
But in the same workspace, if I set laser test to %100, 100ms, it burns a dot instantly and looks very bright.

This only started happening. On my first test at line cut a circle %100, 800m/m cut rate, it burned fine.

<a href="https://imgur.com/ZDp1u0H"><img src="https://i.imgur.com/ZDp1u0H.png" title="source: imgur.com" /></a>
<a href="https://imgur.com/hrkqHUj"><img src="https://i.imgur.com/hrkqHUj.png" title="source: imgur.com" /></a>
<a href="https://imgur.com/zYNIGbx"><img src="https://i.imgur.com/zYNIGbx.png" title="source: imgur.com" /></a>

**Comment by cprezzi** [comment]
It seems you have set your feed units to mm/s (not mm/min), and 800mm/s is probably too height to get burn marks (if your machine can even travel so fast. Try it with 50mm/s or switch default to mm/min.
