### ISSUE TITLE
Not working with Ubuntu 32bit

### ISSUE THREAD

**Issue by robertcasanova** [LaserWeb/LaserWeb4-Binaries#4]
Seems the binaries for Linux work only in 64bit systems.
I tryed to download the source code and i successfully build everything but i have no idea on how to create the executable for my Ubuntu version. Is this documented somewhere?

Thank you!!!

**Comment by tbfleming** [comment]
It's hidden in a file in a branch in a repo: https://github.com/LaserWeb/lw.comm-server/blob/electron_bundler/README-ELECTRON.md

**Comment by robertcasanova** [comment]
Thx @tbfleming i will test it tomorrow!!! =)
