### ISSUE TITLE
A javascript error occurred in the main process

### ISSUE THREAD

**Issue by djjeanb** [LaserWeb/LaserWeb4-Binaries#6]
dear sirs,
i have downloaded the newest version on a clean win 10 machine,
installed java 
installed chrome
but somehow i get this error:
A javascript error occurred in main process details see attachment
followed by a 404 message in the main screen.
what could be the problem?

![laserweb](https://user-images.githubusercontent.com/1922917/34825502-081d016c-f6d3-11e7-8cba-e9b60322d09c.png)
![system](https://user-images.githubusercontent.com/1922917/34825607-7bc69b50-f6d3-11e7-92cf-05a53c89d67a.png)

**Comment by jorgerobles** [comment]
You have another process occupying port 8000. Please check your OS configuration and services.

**Comment by djjeanb** [comment]
the occupying proces is windows NT kernel and system, not something you can close

**Comment by jorgerobles** [comment]
See https://github.com/LaserWeb/LaserWeb4/issues/428#issuecomment-337622494

**Comment by djjeanb** [comment]
yeah tried that but window wo'nt allow blank filenames so i cant make the .env file,

**Comment by jorgerobles** [comment]
Sorry, cannot help with that. You should be able to create file on console.
Btw, if your OS is NT probably  LW won't work anyway.

**Comment by djjeanb** [comment]
Well it works on my other similar windows 10 machine but has the older version installed “out of the box”

I’ll keep digging for more info on this problem

Thanks anyway

 

Van: jorgerobles [mailto:notifications@github.com] 
Verzonden: donderdag 11 januari 2018 16:04
Aan: LaserWeb/LaserWeb4-Binaries <LaserWeb4-Binaries@noreply.github.com>
CC: djjeanb <jean-baptiste@lab-rat.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [LaserWeb/LaserWeb4-Binaries] A javascript error occurred in the main process (#6)

 

Sorry, cannot help with that. You should be able to create file on console.
Btw, if your OS is NT probably LW won't work anyway.

**Comment by djjeanb** [comment]
Got it fixed, i’ll post solution on forum

 

 

Van: jorgerobles [mailto:notifications@github.com] 
Verzonden: donderdag 11 januari 2018 16:04
Aan: LaserWeb/LaserWeb4-Binaries <LaserWeb4-Binaries@noreply.github.com>
CC: djjeanb <jean-baptiste@lab-rat.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [LaserWeb/LaserWeb4-Binaries] A javascript error occurred in the main process (#6)

 

Sorry, cannot help with that. You should be able to create file on console.
Btw, if your OS is NT probably LW won't work anyway.

**Comment by df8oe** [comment]
I do have problem port 8000 is already in use and I want to choose another port for laserweb. Can I do that by configuration file or do I need to build it by myself?

**Comment by djjeanb** [comment]
you can alter the .env file to select a free port.
beware the .env is not a extention its the whole filename, just read the link i provided earlier

**Comment by df8oe** [comment]
Many thanks - works perfectly. Nice peace of software! I will dig into its usage now.
