### ISSUE TITLE
Finishing Appveyor / Travis autocompilation

### ISSUE THREAD

**Issue by jorgerobles** [LaserWeb/LaserWeb4-Binaries#7]
HELP NEEDED

Have no time right now to finish the autocompilation through AppVeyor/Travis of releases, nor manually compilate every change of LW.

I think the only thing it lacks is the proper api keys to distribute the releases.

**Comment by jorgerobles** [comment]
@tbfleming

**Comment by tbfleming** [comment]
I don't know anything about the AppVeyor/Travis setup. Actually, I don't think I've heard the name AppVeyor before. I'll post a help needed to G+.

**Comment by cojarbi** [comment]
Post the procedure I'll take care of it weekly.until this is solved

**Comment by jorgerobles** [comment]
Almost Done. Both appveyor for WIN and travis for MAC works. Thanks @sdesalas for your support.
Have to tweak a bit to release on the same tag (right now each service pushes individual releases)
