### ISSUE TITLE
Any plan to support android device?

### ISSUE THREAD

**Issue by radiolee** [LaserWeb/LaserWeb4-Binaries#8]
I tried run nodejs on android , it's working in demo, but install comm server no luck.

**Comment by jorgerobles** [comment]
Not at all. Sorry.

**Comment by jorgerobles** [comment]
BTW This repo is only for releases, the project to ask for features is https://github.com/LaserWeb/LaserWeb4, thanks

**Comment by radiolee** [comment]
ok,thanks
